### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by BlueHotDog** [LeanKit-Labs/wascally#107]
we've this code:
```
  rabbit.on("*.connection.failed", function () {
    console.log("connection failed");
    process.exit();
  });
```

and this keeps happening, we're running some very long running tasks, and our timeout is very long, like 200000, but this is still happening.

**Comment by BlueHotDog** [comment]
?

**Comment by derickbailey** [comment]
with a very long running task, you may be experiencing network hiccups or TCP/IP timeouts in your network configuration. 

have you set a heartbeat in your connection? you can add a `heartbeat: 30` parameter to your connection string, to set a 30 second heartbeat, for example.

this can help to keep the connection alive during long running tasks or other idle periods of time

**Comment by BlueHotDog** [comment]
how do i add it to the connection string? and isnt that what timeout supposed to do?

On Tue, Nov 24, 2015 at 4:54 PM Derick Bailey <notifications@github.com> wrote:
with a very long running task, you may be experiencing network hiccups or TCP/IP
timeouts in your network configuration.

have you set a heartbeat in your connection? you can add a heartbeat: 30 parameter to your connection string, to set a 30 second heartbeat, for example.

this can help to keep the connection alive during long running tasks or other
idle periods of time

**Comment by derickbailey** [comment]
timeout is how long it will wait for the initial connection to be established

heartbeat is a "ping" of sorts, across that connection, to make sure the connection stays alive and to more quickly deal with the connection dying when it does happen

for a connection string, you can add a `?heartbeat=(seconds)` parameter, where (seconds) is the number of seconds you want to use for the hearbeat. `heartbeat=5` for example, for a 5 second heartbeat. 

you can read more about heartbeat here https://www.rabbitmq.com/heartbeats.html

**Comment by BlueHotDog** [comment]
But from your code, i'm seeing that the default is 2000, so no way i'm reaching 2000s..

seems like publishing a dummy message with an interval solves the trick, 
(setinterval(publishdummymsg,2000))

**Comment by BlueHotDog** [comment]
ok, seen the PR.
got it! 

thanks.

**Comment by BlueHotDog** [comment]
well, with the new version we've another issue: zombie consumers.

Consumers never removed(if a consumer dies unexpectedly).

**Comment by arobson** [comment]
@BlueHotDog - I'm not sure how that's possible. When a connection is terminated, the consumers are dropped from RabbitMQ. Wascally will continue to re-connect and re-establish subscriptions (re-creating consumers) whenever possible. If the process itself dies, Rabbit should see the connection loss and reflect that by decrementing the consumer count (since the channels are also destroyed when the connection is terminated).

**Comment by arobson** [comment]
@BlueHotDog - wascally is no longer under active development. [rabbot](https://github.com/arobson/rabbot) has taken its place. The API is almost identical with several enhancements. I can't promise you won't have the same problems, but because rabbot doesn't have the same aggressive failure semantics, it's far less likely that you will see zombie connections/channels popping up on your services. If you're still using wascally, give rabbot a try and see if this doesn't resolve the issue.
