### ISSUE TITLE
Are rejectUnhandled and onUnhandled working when using dead-lettering?

### ISSUE THREAD

**Issue by n321203** [LeanKit-Labs/wascally#121]
I am learning Wascally, and I see some strange behavior in relation to rejectUnhandled / onUnhandled in combination with dead-lettering.

I have a single exchange with a dead lettering enabled. If I reject a message inside a handler, the message is correctly routed to the dead-lettering-exchange with a new dead-letter-routing-key. 

If I use rabbit.rejectUnhandled(), I expect unhandled messages to be automatically rejected and routed to the dead-letter-exchange. This does not happen, in fact rejectUnhandled does not seem to do anything.

If I use rabbit.onUnhandled( handler... ), it correctly picks up unhandled messages and I can message.reject() them there, but the message is not routed to the dead-lettering-exchange until I close the process and re-open it.

Are these functions intended to work together with dead-lettering?

**Comment by arobson** [comment]
@n321203 - the `rejectUnhandled` and `onUnhandled` only refer to messages delivered to your service that no registered handlers would process. It's there to let you know that your topology is routing messages to your queue but your service was not configured to do anything with them.

Dead-lettering has more to do with how Rabbit handles rejected messages.

**Comment by n321203** [comment]
Yup, I am intentionally sending messages with type names that I have no registered handlers for. When `rejectUnhandled` is enabled, I expect such messages to get rejected, and then delivered to the dead-lettering-queue

**Comment by arobson** [comment]
@n321203 - checkout [rabbot](https://github.com/arobson/rabbot) as wascally is no longer being actively developed.

The scenario you described should work but you would be hard pressed to have it work within the same process since the message handler for the type would need to exist in order to process messages coming from the queue bound to the dead-letter-exchange, but if that were the case, a registered handler would prevent the reject unhandled from happening within that process in the first place ...
