### ISSUE TITLE
How is concurrency handled?

### ISSUE THREAD

**Issue by 21stio** [LeanKit-Labs/wascally#128]
Hey,

how is concurrency handled? 

When using `rabbit.handle` does it start sth like a worker that pulls a message, waits for  `ack / nack / reject ` and pulls the next one? 
Or does just as much as it can?
Or does `rabbit.handle` just pull one message and you have to call it another time to get the next message?

Thanks in advance :)

**Comment by derickbailey** [comment]
wascally will let your code pull in more messages than it can really handle, really

i once had a backlog of about 65,000 message in a queue due to a bug in my code. i fixed the bug, re-deployed, and ate all of the memory on my server when my code tried to load all 65,000 messages all at once. 

to fix that problem, i added the `limit` setting (aka [consumer prefetch limit](https://www.rabbitmq.com/consumer-prefetch.html)) to my consumer. i think i put the limit somewhere around 10 or 20 messages at a time, but i could have set it higher. 

having the limit in place allowed me to process the messages in smaller chunks, preventing me from crashing my app server.

if you want to process one message at a time, set your consumer limit to 1. wascally defaults to `noAck: false`, meaning you will be required to manually ack your messages. this, with the limit of 1 message, means you will need to finish processing a message before the next one starts.

**Comment by 21stio** [comment]
Awesome, that's the answer I was looking for, thanks a lot

**Comment by arobson** [comment]
@derickbailey @21stio - setting the consumer limit to 1 will slow things down a lot but guarantee message order.

If you need more concurrency and want to preserve message ordering within a particular context, you can use my [hashqueue](https://github.com/arobson/hashqueue) library to create N in-memory worker queues and have work distributed across those using consistent hashing. You'll need to have something that identifies the context for each message (we use correlationId on the message) that it can hash across.

HTH!
