### ISSUE TITLE
How does one undo a startSubscription?

### ISSUE THREAD

**Issue by djMax** [LeanKit-Labs/wascally#132]
I'm getting exceptions about "Channel ended, no reply will be forthcoming" thrown against some Promise I don't seem to have. If I call destroy on the queue that comes back from startSubscription, I get an error about getMessageCount not existing. Basically I'm unable to start a connection, subscribe to a queue, and then close cleanly.

**Comment by dvideby0** [comment]
any update on this? @djMax did you ever get this sorted?

**Comment by djMax** [comment]
Yeesh. I can't remember. I think we got around it, I'll ask other folks how tomorrow.

**Comment by dvideby0** [comment]
Thank you. Much appreciated

**Comment by arobson** [comment]
@dvideby0 @djMax - Have you taken a look at [rabbot](https://github.com/arobson/rabbot)? It's the successor and intended replacement. The API is almost an exact replica with a few additions. The biggest changes are around some of the failure behaviors because, honestly, wascally tries to recover from too many things. While I don't recall this being an issue we've run across in production, it's in the class of problems I was solving when I reworked the connection and channel management.

Sorry its been causing headaches.

**Comment by arobson** [comment]
@djMax @dvideby0 - also worth noting: https://github.com/squaremo/amqp.node/issues/250. I _might_ have resolved the edge cases that can trigger this, but it's effectively a race condition in amqlib.
