### ISSUE TITLE
every connection creates a response queue, even if it doesn't need it

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/wascally#26]
as reported on my Rabbus project: https://github.com/derickbailey/rabbus/issues/1

i created a sample connection using this code:

```js
var Rabbit = require("wascally");

Rabbit.configure({
  connection: {
    // ...  your connection info here
  } 
}).then(function(){;

  console.log('connected');

});
```

and a response queue showed up in my queue list... i have not defined any queues, i haven't tried to do any request/response work... all i did was create a connection, and the response queue showed up in my queue list.

it shouldn't create a response queue until i need one... until i'm doing request/response work.

how can i prevent these extra queues from showing up?

**Comment by arobson** [comment]
@derickbailey, @episodeyang - Happy New Year :tada: This is actually intentional. If it didn't behave this way, your first request message couldn't even be sent until after the response queue had been created on the server. Since a a single queue without messages isn't a performance/resource consideration, I'm curious as to why this feels like a bug. I'm reluctant to change this behavior as it would add complexity to sending a request message (having to check for response queue and create it if missing and only then publishing the message) as well as introducing latency to the initial request that can easily be avoided.

Do the queues linger after the service is stopped? That would be a defect and I'd definitely want to address it.

**Comment by episodeyang** [comment]
I will defer the opinion to @derickbailey since he is more experienced. :P

**Comment by derickbailey** [comment]
Happy New Year :tada:! And what a way to bring it in - with me having nothing better to do with my vacation, than complain about open source on github issues :D

Ok, I get the reasons why. I just don't agree with the reasons. There's 2 potential arguments that I have against the feature being automatic. 

There's a very minor resource/performance concern - having the extra queue, extra channel, extra subscription. This won't be an issue unless you have a ton of connections open ... probably far more than I'll ever have open. So, ok. Not really going to play the resource/performance card, here.

More importantly is the principle of least surprise. 

As an example, one of my systems has 8 separate connections open, at this point - 8 separate processes that each need their own connection. So now I have 8 extra queues that I don't need.  This is very unexpected.

It was also surprising to me when @episodeyang reported this "feature" on my rabbus project, as a bug. I thought I had a bug or an extraneous queue being created and not destroyed. I spent some time looking at my code, only to realize it was wascally doing this.

I'm not fond of using my time like this, or having to explain why things like this are done when they are not necessary in the majority of cases. At the moment, I have 1 use case for request/response in the dozens of scenarios in which I am using wascally. If there was an 80% + use case for this return queue, i don't think it would be quite so surprising.

Personally, I think it would be better to take the minor perf hit on the first req/res use, rather than having to explain this to people after they spend time digging, looking for a problem. Or provide an option in the connection to pre-build the response queue and subscription, when you know you will be using req/res. 

At a minimum, I would like to see an option to prevent this extra queue from being created.

**Comment by arobson** [comment]
@derickbailey - You can see how far behind I'd gotten on Rabbit related things, but this is an interesting write-up on a new feature for 3.4.0: https://www.rabbitmq.com/direct-reply-to.html. You can see how they're describing how their new feature removes the need for what wascally is doing in this issue. I will likely work on a patch that will use direct RPC in a configurable manner.

**Comment by derickbailey** [comment]
this gets even more fun with a realization that i had yesterday: i need a long-living, persistent reply queue

in my client system, replies are becoming critical. i am sending out requests for jobs to be worked, and I must receive a reply telling me the job was done (or errored, or whatever). 

one of the other requirements in my system, is that the central hub (the brain of the system) is able to shut down, come back up, and continue processing the job schedules that it was working previously. in looking at this requirement, one of the major hurdles that i have to implement is long living, persistent reply-to queues. 

when my main process shuts down and comes back up, it needs to be able to receive the replies that were sent while it was down. having temporary queues like wascally currently does, or even the direct reply-to queue in that new feature, is not going to work in this scenario.

i think it would be great to support the direct reply-to (and i sounds like this can already be used, just by specifiying "amq.rabbitmq.reply-to" as the reply-to queue, and publishing a message to that queue). not everyone will be able to do that (me included, in at least one of my systems running RMQ 3.3.5), and wascally's current implementation of req/res won't work for me in another scenario...

i'm probably going to rebuild my rabbus req/res setup to allow for this type of persistent queue as an options instead of using whatever wascally builds in. i don't know what that will look like, over-all. it may be a complete rewrite of res/res capability, but i want to take advantage of wascally when i can (and not duplicate code)

fun

**Comment by derickbailey** [comment]
re-reading that direct reply-to feature and it definitely won't work for what i need. the no-ack requirement, the default exchange requirement... nope.

**Comment by arobson** [comment]
I follow. I would say that's not a typical messaging pattern (long-lived/resilient RPC). Have you considered not treating this like request/response? You could just treat this like simple message handlers and persistent queues. Typically, the only reason I use request/response(aka RPC) on a message broker is so that I can get competing consumer style scale-out on request handling. Otherwise, there are other messaging patterns you can take advantage of that don't get you into some of these challenging nuances you're hitting. If you're not familiar with it already, check out [Enterprise Integration Patterns](http://www.enterpriseintegrationpatterns.com/) and the [book](http://www.amazon.com/Enterprise-Integration-Patterns-Designing-Deploying/dp/0321200683). To the best of my knowledge, this is the best single source for description and discussion of various messaging patterns and architectures. It _may_ provide you with some insights into the challenges you're facing even if you need to stick with specialized RPC like you've described.

Granted, I know almost nothing about your specific system and I appreciate that every system has its own unique needs, just trying to be helpful :smile:

**Comment by derickbailey** [comment]
i hate calling this RPC, because it's not really RPC. i get it that most people do RPC this way, and that it's common... but i'm a stickler for semantics :D

yeah, i've got that book - started reading it about 6 years ago, when i first started doing composite application design and distributed systems (using C#, webspheremq and XMS.NET at the time - ask John Mathis if he remembers Digital Logbook - it's where I cut my teeth on all this stuff). personally, i found that book to be soooo painfully dull to read. :P but it's a tremendously valuable reference book for patterns. i'll look through it again and see if any of the other patterns match my current needs better than this. 

one of the reasons i decided to go w/ req/res in this case, was the way it simplified my code. with the built-in use of correlation-id and reply queue, it made my life pretty easy. but i've got correlation-id in rabbus now, so it might not be such a daunting task to do this without req/res

**Comment by arobson** [comment]
@derickbailey I think that eventually I would like to provide a way for consumers to plug in their own req/resp "strategy" (with the present method and the new direct-reply as built in ones to choose from). I've marked this for 0.2.1 because I've just got too many other things in other libs that are immediate needs. Hopefully I'll have 0.2.0 done by Monday. #famouslastwords

**Comment by derickbailey** [comment]
sounds good, yo. i like the idea of pluggable strategy and totally understand having other priorities for wascally. this is a nice-to-have, not a critical bug right now.
