### ISSUE TITLE
Basic Demo for Simple Worker Queue

### ISSUE THREAD

**Issue by nicholaswyoung** [LeanKit-Labs/wascally#33]
I need a basic worker queue, similar to [Sidekiq](http://sidekiq.org) or [Kue](http://learnboost.github.io/kue). The publisher doesn't need to receive responses from the worker, so this should be a simple unidirectional queue pattern &mdash; and yet, I can't see how to implement it with Wascally. 

Any tips?

**Comment by arobson** [comment]
@nicholaswyoung - did you look at https://github.com/LeanKit-Labs/wascally/tree/master/demo/pubsub? This has the slightest bit more than what you'd need since the publisher and subscriber do a bit of coordination up front.

How familiar are you with RabbitMQ/AMQP itself? The publisher confirms are the broker telling the publisher, "I have successfully routed a message", not anything beyond that. The consumer acknowledgements are your worker telling the broker, "I successfully handled this message, you can permanently delete it" and don't send anything back to the publisher.

Let me know where you're running into specific issues. If you haven't read RabbitMQ's docs, I can't recommend this enough. Trying to use wascally without a pretty good understanding of RabbitMQ/AMQP is probably going to be confusing.

**Comment by nicholaswyoung** [comment]
@arobson I'm decently familiar with AMQP/RabbitMQ, but not an expert by any means. I did see the pubsub demo, and it confused me more than anything. Maybe that's because I'm not that well versed in AMQP lingo, but the innards of Wascally and how to configure it are a bit perplexing.

As I understand AMQP, I don't have to define an exchange and bind queues to it *unless I want explicit routing through those exchanges* (I was planning to use the "default exchange, as I think they call it in the docs). My use case is extremely simple, and all I need is one instance of a publisher per application instance, and a handful of workers to process the jobs.

This sounds like the best way is to create a fanout queue, which I've done successfully in older AMQP libs for Node, just not Wascally. Any insight you have that would help me break down the pubsub demo into only the chunks I need would be helpful.

**Comment by arobson** [comment]
@nicholaswyoung I would not recommend using the built in exchanges, even for the simplest use cases, but that's just my opinion.

The topology class is setting up shared topology between two services. This is done to eliminate the possibility of race conditions (e.g., the subscriber starts first, tries to bind its queue to an exchange but it hasn't been created yet). You don't _have_ to use a shared topology approach like this, but I've found that you run into far fewer issues and avoid having different definitions of exchanges or queues across your services.

### configuration
The easiest way to setup wascally is through the `configure` call. The `connection` property is pretty self explanatory (I hope). The exchange, queue and binding blocks provide a list of each of those items which need to be created on the server. In the event those items already exist and match the configuration specified, the server no-ops them. The nice thing is that any commands that rely on those primitives existing on the server will be delayed until the underlying calls are resolved and, should you lose connectivity to the broker, once it is re-established, wascally will re-build the topology (a common need in systems that use auto-delete exchanges or queues).

Here's a very simple example of a topology like you have described:

```js
var rabbit = require( 'wascally' );

// create an exchange, 'work', and a queue, 'work-queue' and bind the exchange to the queue
rabbit.configure( {
    connection: {
        user: 'bunneh',
        pass: 'rabbit',
        server: [ '127.0.0.1' ],
        port: 5672,
        vhost: '%2f',
    },
    exchanges: [
        { name: 'work', type: 'fanout', durable: true }
    ],
    queues: [
        { name: 'work-queue', durable: true } 
    ],
    bindings: [
        { exchange: 'work', target: 'work-queue', keys: [] }
    ]
} );
```

### publishing
To publish to an exchange you've declared in the configure block, you simply call: 

```js
rabbit.publish( 'exchangeName', { 
    type: 'workItem', 
    body: { /* the message you want to send */ } 
} );
```

Wascally will track this published message's status via publisher confirmation. If the channel or connection is shutdown without a confirm, wascally will attempt to re-send this message after a connection and channel have been re-established.

### subscribing
When subscribing, please be sure that you have assigned message handlers to incoming types of messages (more on this in a minute). If you had declared the queue in the config block above with `subscribe: true`, it would have automatically started consuming messages on that queue the moment the server confirmed the queue existed/was created.

In this case, I left that off so you can setup your handlers at anytime before explicitly starting the subscription like this:

```js
rabbit.startSubsciription( 'work-queue' );
```
With wascally, it doesn't matter what queue the message arrives on; any message arriving on any queue you've subscribed to will be handled by matching the type of the message with the handler you registered for that type.

### handling
To register a handler for a type of message use the `handle` call:

```js
rabbit.handle( 'workItem', function( msg ) {
    // do something with the message
    msg.ack(); 
} );
```

That's pretty much all you really need to get started. I haven't checked it out myself, but @derickbailey has built [rabbus](https://github.com/derickbailey/rabbus) on top of wascally and I think it provides a much higher level of abstraction. Wascally sits somewhere between generic messaging patterns and AMQP.

I hope that helps disambiguate things, but I'm afraid I don't know how to break it down much further than this without specific questions.

**Comment by nicholaswyoung** [comment]
This really clears things up. I'll give it a shot in the morning, and ask specific questions if I have them. Thank you for the detailed explanation!=

**Comment by derickbailey** [comment]
@nicholaswyoung FWIW, I built [rabbus](https://github.com/derickbailey/rabbus) to give me an easier way to manage things since I found myself repeating the same code over and over again. I prefer to have individual objects for each of my publishers and subscribers, based on the message type, as well. If you do look at rabbus, you'll want the pub / sub objects, which are configured as a fanout exchange and queue bindings. 

+1 to not using the default exchanges and queues. these are nice to have for a "getting started" demo, where you don't want to bother people with an explanation of RMQ topology... but I don't recommend using them for production purposes. They do work, of course, but they will limit your ability to grow your application configuration in a meaningful way.

and i have a question / comment: with a fanout configuration, all of the queues that are bound to the exchange with a matching routing key will receive the message. are you wanting all of your queues / handlers to process each message? or were you just looking to have multiple handlers up and running to handle the amount of traffic you'll be sending through the exchanges?

**Comment by nicholaswyoung** [comment]
@derickbailey It's the latter case. If one message handler receives and successfully processes the job, it should be marked as done and removed from the queue. All jobs need to happen once, in an ideal scenario &mdash; though I could easily configure them to be idempotent. 

Am I going down the wrong path?

**Comment by derickbailey** [comment]
@nicholaswyoung yeah, I think you're heading down the wrong path with fanout. what you're describing is more of a direct exchange

where a fanout exchange will send the received message to all queues that are bound to the exchange / routing key combination, a direct exchange will send the message to only 1 queue that matches the exchange / routing key combo. even if there are multiple queues bound to the exchange with that routing key, only 1 of them will receive the message. the way it picks the queue is simple round-robin style.

the rmq examples have a pretty good description of what you're looking for, here (the ruby version) https://www.rabbitmq.com/tutorials/tutorial-two-ruby.html

w/ Wascally, the default mode of handling messages requires acknowledgement of the message being processed - this is half the equation from that tutorial, already. the other half is setting up the direct exchange and queue. 

i have a slightly old demo of this configuration at https://gist.github.com/derickbailey/4c61f4ae3f470946f83f

**Comment by derickbailey** [comment]
also - if you're interested in this w/ rabbus, the direct exchange is baked in as the "send / receive" types

**Comment by nicholaswyoung** [comment]
@derickbailey @arobson I'm not sure what's happening, but everything seems to work fine when configured as a fanout exchange. The moment I reconfigure as a direct exchange, no messages are sent or received.

Maybe there's a specific piece of configuration I'm missing?  https://gist.github.com/nicholaswyoung/78c7e95607a68f514a29

**Comment by derickbailey** [comment]
did you delete the exchange before re-creating it?

if not, that is the problem. rabbitmq will not re-define an existing entity (exchange, queue, etc). If you try to re-define an existing entity, it silently doesn't dot anything and can cause the exchange to not work. 

i ran in to this exact problem over the weekend, and had to manually delete an exchange so it could be re-built correctly, this morning.

**Comment by nicholaswyoung** [comment]
@derickbailey I didn't.... I bet that's the error. I had no idea it stores exchanges like that.

In your opinion, would it be better to use Rabbus for this?

**Comment by derickbailey** [comment]
"better" is a matter of preference... i don't expect Rabbus to fit the opinions of everyone that wants to use Wascally. I'd recommend using Wascally for now, and understand how it works. If you find that you want to trade flexibility for a smaller API, then Rabbus might be a good idea. But seriously - Rabbus does limit your flexibility. I built the object pairs with very specific opinions. If you need something other than what they provide, stick with Wascally directly (or use both, as needed... since rabbus sits on top of wascally).

**Comment by nicholaswyoung** [comment]
@derickbailey Clearing RabbitMQ's cache fixed the issue. I think everything is working as expected now. Thanks to you and @arobson for walking me through this!
