### ISSUE TITLE
with multiple handlers in a single process, if one nacks the message will infinite loop between handlers

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/wascally#36]
scenario:

* single nodejs process
* 2 listeners for the same message type, on the same queue
* 1 of the listeners `nack`'s the message
* other listener `ack`'s the message
* the message will be put on infinite loops, passing between the two handlers

see https://gist.github.com/derickbailey/a962cb12cf51b2b26960 for a demonstration of this.

i expect (need) the `ack` the to stop the message from processing any further. currently, that is not happening. 

take the code from the gist above, and run the `receiver.js` first. then run the `sender.js` file. you will see a single message sent across the exchange / queue. once it is picked up by the receiver, the message will ping-pong between the two handlers inside of the receiver.js file, infinitely. no matter how many times the `msg.ack()` is called, it will still get pushed to the other handler and `msg.nack()` will be called again, sending it back to the 1st handler which will `ack()` it again, and round and round and round forever.

if you comment out the `handleMessage2()` call in the receiver, the message acks and it is removed from RMQ. but if you have both `handleMessage()` and `handleMessage2()` running, it will infinite loop, passing the message round in circles.

**Comment by derickbailey** [comment]
FWIW, this is "OMGTHESKYISFALLING" level bug for me, right now. I've spent 3 days tracking down the issue, from my app code, to my rabbus library and down to the demo code above. all the while, production issues are killing me.

yeah, i'm being "that guy" ... just hoping a desperate plea can bump the priority on this.

**Comment by arobson** [comment]
@derickbailey - I'm not sure I understand why you would have two handlers for the same message type that each result in a different resolution. I would *really* like to understand the use case for this.

My curiosity aside, the reason for this has to do with a few things:
 1. wascally uses postal to dispatch messages to handlers - all handlers with that message type will receive that message
 2. message resolution is unique to the message tag - in other words, Rabbit is not giving you two messages, but a single message with a single tag. When you provide conflicting resolutions, you're getting into a 'last write wins' scenario - whichever resolution (ack/nack/reject) is the last to fire before wascally does a batch resolve will be the operation that takes effect.

This isn't something wascally can solve for you. You will run into this issue with any lib - a message can only have one outcome (ack, nack, reject). I recommend having a single handler that dispatches the message to downstream functions and then determines a single resolution/outcome.

Let me know if this makes sense, I definitely want to help where/if I can!

**Comment by derickbailey** [comment]
## why i need this

this goes back to the previous conversations we've had about my not being able to use request/reply, and how i am using the `correlationId` to ensure the right object is processing the messages that come back from external systems.

i'm building a job scheduling system that allows multiple schedules to be active at any given time. each schedule contains knowledge of what jobs and steps it should run, in what order. for each step in each job, the schedule sends a message across a queue. an "agent" picks up the step request, runs it and sends back multiple messages to tell the schedule what the status of the step is. when a given step hits the "complete" status, the schedule fires off the next step. 

given a single schedule instance in memory, this works perfectly fine. 

the problem noted above comes in to play when there are multiple schedules running at the same time. there is a lot of complexity in the scheduling rules and when to fire off which job and step, combined with the need to track status and progress along the way, be able to re-run failed steps and jobs, and track the actual schedule execution history as it happened vs how it was originally configured. 

given all of this and my propensity for OO style coding, each schedule instance is it's own object in memory. each schedule instance has a listener for the 'status' of steps. the status messages all have a correlationid that points the message to the right schedule instance.

i am using the correlationid to determine whether or not a given schedule instance and it's status listener can handle the message. if it cannot, it nacks the message. if it can, it handles it appropriately. the actual logic of the correlationid is handled inside of my rabbus library, so the schedule instance never even sees messages that it can't handle. 

## what wascally is doing

> wascally uses postal to dispatch messages to handlers - all handlers with that message type will receive that message

given a single queue with multiple listeners, rabbitmq will hand off the message to a single listener, one at a time, round-robin style. if a listener nacks, the message goes to the next listener. if that listener acks, the message is processed and rmq stops handing it off to other listeners.

the behavior of postal dispatching messages to all handlers for a given type does not technically break this behavior at the rmq level... but it does add a new layer on top of rmq, and changes the expectations.

were I using amqplib directly (as I've done in the past...) and had a new listener for each schedule instance, the message woudln't continue bouncing around forever. once i ack it, it will stop moving around as it has been ack'd. 

i can see the advantage of having postal dispatch the messages based on message type. this would let you aggregate multiple message type through a single queue, or let you aggregate multiple queues through a single message type. 

> This isn't something wascally can solve for you.

it's something that is not solved by wascally currently, but at the same time it is something caused by wascally's use of postal.

postal is, in effect, taking my `direct` queue and repurposing it as a `fanout` queue (pub/sub style). this is breaking my system.

## why allow multiple ack/nack/reject calls?

i have to ask the question, of why wascally allows mutliple ack/nack/reject calls to be made on a single message? how is that practical, and where is it beneficial? how are you using that?

if you have multiple handlers for a single message type, which one acks the message? do have all of them ack or nack? 

## allow me to stop the message from continuing, middleware style

in thinking about options to solve this, express middleware and the chain-of-responsibility pattern comes in to mind. 

```js
rabbit.handle("some.message.type", function(msg, next){
  if (!something){
    msg.nack();
    next();
  } else {
    msg.ack();
  }
});
```

if i had a mechanism like that, i could stop processing in the handlers whenever i need to, or let them all run by always calling `next()`. this could be inverted and it could be a `done()` call instead, telling the handlers that no one else needs to process this message.

## a workaround 

> I recommend having a single handler that dispatches the message to downstream functions and then determines a single resolution/outcome.

i might be able to do that as a workaround. i still say there should be a better solution, though.

**Comment by derickbailey** [comment]
ultimately, the current behavior seems to be at odds with the idea of correlationId. I need to be able to use the correlationId to determine which handler can process which messages. 

right now, the suggested workaround is to not use a correlationId, but to do more of a lookup table style where i have a single handler that takes a piece of data from the message, does a lookup for the object instance that i need, and forwards the original message to that object.

**Comment by arobson** [comment]
@derickbailey - I think I follow - you're saying that each schedule instance in memory registers its own handler with wascally for the same message type. so that the code might be

```javascript
var MyScheduler = function( id, rabbit ) {
    this.id = id;
    rabbit.handle( 'aThingToDo', this.doAThing() );
}

MyScheduler.prototype.doAThing = function( msg ) {
    if( this.id !== msg.correlationId ) {
        msg.nack();
    } else {
        // do stuff
        msg.ack();
    }
};
```

You will need the latest postal to pull this off, but this should work:

```javascript
var postal = require( 'postal' );
var rabbit = require( 'wascally' );
var schedulerTasks = postal.channel( 'schedulerTasks' );

// pretend we setup rabbit ...

rabbit.handle( 'aThingToDo', function( msg ) {
    var newTopic = 'aThingToDo.' + msg.correlationId;
    schedulerTasks.publish( newTopic, msg, function( result ) {
        // if result.activated is true, then you have a scheduler that is listening for this message
        if( !result.activated ) {
            msg.nack(); // sends the message back from whence it came...
        }
    } );
} );

var MyScheduler = function( id, rabbit ) {
    this.id = id;
    // note: for multiple message types, you can subscribe to '#.' + id
    // then determine the right function to call w/ the message based on the msg.type 
    schedulerTasks.subscribe( 'aThingToDo.' + id , this.doAThing() );
}

MyScheduler.prototype.doAThing = function( msg ) {
        // do stuff
        msg.ack();
};
```

There's certainly more conversation that could be had around approach but at the end of the day, you know your system best and you have to be happy with the design because you work on it every day. I may have gotten some of the syntax a bit wrong since I'm literally just typing this into a comment window, but I do hope this resolves your issue w/o the need to do heavy redesign.

**Comment by arobson** [comment]
@derickbailey - hopefully you won't need it, but if you want to try and work through this issue at some point and have screen hero, I'd be happy to see if we can't get the above approach working so you're not stuck.

**Comment by derickbailey** [comment]
i've been working on getting this idea in place, but haven't had any luck yet. so far, it seems to be having the same problem... though not as bad as before. i'm still ending up with multiple listeners handling the incoming message, even when i have a correlationid.

not sure what to do at this point.

**Comment by arobson** [comment]
If you're only calling rabbit.handle( 'messageType' ) one time (and you should only be doing this once per type), there's no way for the handler to get the same message multiple times. The example above is intended to subscribe to the type once and use a postal channel to publish to a unique topic. Each scheduler should only subscribe to the topic matching its id once; making it impossible for a scheduler to receive a message not intended for it.

Selective consumer is actually an anti-pattern for AMQP/RabbitMQ - nacking messages to send them back to the queue does not guarantee that a different consumer will get the message next time. If you want different consumers to get messages based on topic, you would use a topic exchange with specific routing keys or a consistent hash exchange and correlationId.

I may try to put together an actual working gist to demonstrate the pattern in something beyond the over-simplistic code I have in the comment above.

**Comment by derickbailey** [comment]
yet another stream of thoughts, here. 

> If you're only calling rabbit.handle( 'messageType' ) one time (and you should only be doing this once per type), there's no way for the handler to get the same message multiple times.

that's the problem i ran in to. my intermediate layer (rabbus) creates a handler per instance. 

> Selective consumer is actually an anti-pattern for AMQP/RabbitMQ

is this documented somewhere? i've never seen anything that says this (not that i have extensive community knowledge...) and it is a common / well known pattern in messaging

> nacking messages to send them back to the queue does not guarantee that a different consumer will get the message next time.

i don't need the message to go back to the queue in this case. i need postal to stop dispatching it when i've handled it.

right now i see my options as:

0. hack around the use of postal, by setting a `.isHandled` attribute on my message (that's what i'm doing atm)
0. restructure the system to have a single message receiver, using an in-memory lookup for the specific schedule instance, forwarding the message to the right one
0. restructure the system to have a queue per schedule instance

option 1 is the easiest, but probably the worst. it "works" but it takes advantage of things in a way that are not guaranteed to remain the same in the future ... notably, that the msg getting passed around by postal is the same object instance for all handlers. 

option 2 is a possibility, but a fair amount of change. i'm already tracking my in-memory schedule instances for another feature set. 

option 3 seems like it would add a ton of overhead to my RMQ topology. each schedule instance would require it's own dedicated queue - this would involve standing up / tearing down a lot of queues (and exchange bindings) on any given day... possibly dozens or hundreds of them once the full nightly / weekly / monthly / quarterly / yearly job schedules at this healthcare network are in place. 

do you think the constant topology changes are going to be a better approach than nacking messages? 

correlationId seems the best option in my current experience, but the dispatching that postal does requires me hacking option 1 in place like i have done. i would really like to see this as a first class feature in wascally (or postal?), to let me stop postal's dispatching of a message once it has been handled.

i'm trying to understand all of this, so i can make the best decision for my system. 

---

thanks for you time and help on this, by the way. i know i'm complaining a lot. i'm confused, and that is coming out poorly in my communication. i really do want to understand, and i really do want to keep using wascally. i've tried all the other nodejs libs for rmq, and wascally is easily the nicest to work with. i just need to get my head wrapped around this completely, so i can make the best decision for my system.

**Comment by arobson** [comment]
@derickbailey - 
## [Selective consumer](http://www.eaipatterns.com/MessageSelector.html)
Selective consumer is a fairly common pattern but kinda dangerous as it assumes you have access to nearly unbound computing/network resources. Instead of routing intelligently, you just blast copies of messages all over the dang place and make your consumers responsible for filtering out the crap they don't want/need. A large reason behind Rabbit's routing is to avoid this kind of strategy by making it possible for you to route/filter messages *before* they get to the consumer so that your consumers are only receiving messages they care about in the first place.

I don't know that you're going to find anything that explicitly says, "you should never use selective consumers with RabbitMQ" - but the pattern itself goes counter to how AMQP is designed (and more specifically, how Rabbit is implemented). Sending messages back to the queue is always expensive and can trash FIFO behavior so that your system isn't processing messages in the order they were sent. A message that has to be re-queued several times before it happens to get assigned to the right consumer will be less likely to get handled in relative order the more consumers that exist. It can also become a perf hit across several dimensions: 

 1. you've just made all your interactions with Rabbit more chatty - instead of just getting the message pushed to you and handling it, you're going back to Rabbit multiple times to nack the message and then have it pushed back to you.
 1. the constant-reshuffling of messages in the queue is a drain on server resources
 1. your event loop is now wasting cycles deserializing, routing and rejecting the message multiple times instead of just handling the message once.

## A note about delivery and ordering
Last I dug in - when there are multiple consumers on the queue, RabbitMQ is opportunistic about pushing messages down to them. You don't really get round-robin like you're thinking unless you set each consumer to QoS of 1 and even then, if you nack a message back to the queue, nothing prevents Rabbit from redelivering the message to the same consumer on that queue later - it's all "luck of the draw". This may have changed at some point, but I've read nothing to indicate that it has.

## Option 1 - it's a trap
This is problematic for a few reasons, the most significant being that you get no guarantees around subscription ordering. Technically, you could do this without changes to postal, but I wouldn't go this route. Wascally publishes to a dispatch channel on postal a single time per message received. Every time you call 'handle', wascally is passing your callback to the postal channel's subscribe call. The message instance is the same, to my knowledge. It is an anti-pattern in messaging (and postal usage) to take advantage of this for the reason you mentioned above and also because __there is no guarantee around order of execution__. I know it's tempting to take this approach since it's pragmatic and would require the least amount of coding up front, but if you try to add tests around it (or heck, add logging around it) - you'll see that this gets unpredictable from one run to the next.

## Option 2 - the cleanest option
You don't actually need an in-memory lookup. Here's what you need for a simpler version of option 2:

 * 1 handler for a given message type
 * That handler publishes the message to a shared postal channel, we'll call it "schedulers"
 * When it publishes to the channel, it uses a topic comprised of the message type + the correlation id "task.100"
 * Each scheduler should subscribe to the "schedulers" channel on message type + its id - "task.100"
 * This will guarantee that a scheduler instance will _only receive a single copy of messages intended for it_. They can't get messages intended for a different scheduler instance and they will only ever get a single copy of the message.

This allows your schedulers to have full control over what messages they receive and, better still, it decouples them from wascally so that you could literally put *any* transport in wascally's place and still get messages to your scheduler instances (and you can test them easier this way). You can also independently control when the scheduler subscribes/unsubscribes to those messages so that you have fine-grain control over what messages are getting processed and when. It's really an all-round win - you get more features, better testability and better control.

## Option 3 - The one with a lot of scale out
This option won't really solve your problem unless you want a Node process per scheduler. Wascally doesn't do any kind of coordination of messages across queues - it basically treats all messages from all queues the same. Re-building localized queues would solve for this but also require a good bit more memory/CPU to manage. The .Net lib (very similar to wascally) that I wrote *has* to do this because you are literally processing messages in Parallel and because .Net uses OS threads, your handler's context can get squashed by the OS and cause the messages to get handled out of order (it's so bad, you almost never see them get processed in the right order w/o intervention).

I personally wouldn't enjoy running a separate instance of Node for each scheduler. There are intermediate steps that you can take between where you are now and there, but that's a different discussion and would just introduce your need for more infrastructure or new features.

**Comment by derickbailey** [comment]
after giving this some more thought over the last few days, I'm likely going to go with option 2 that you described. 

turns out this is a pattern i've done before, with client side js and websockets: http://lostechies.com/derickbailey/2012/04/19/decoupling-backbone-apps-from-websockets/ - so it's already familiar, and likely will end up being a better solution. 

thanks again for all the feedback and inquisition on this!
