### ISSUE TITLE
Making sense of demo

### ISSUE THREAD

**Issue by neverfox** [LeanKit-Labs/wascally#38]
I cannot seem to make any sense of the demo. I'm starting the publisher first, then the subscriber. The subscriber sends a request every 3 seconds and the publisher picks up all of them and then starts the long running for-loop on the first one. The subscriber doesn't receive anything until the for-loop is done (which I didn't expect). It keeps sending requests (about 43-44 of them) and the requests pile up as unacked (the publisher is sent the message but is busy running that long for-loop, so they never get a chance to expire). Then the publisher starts running the loop again and again for all of those requests (as I discovered by adding a `console.log` to for-loop itself). However, only the first request sends any messages back to the subscriber, which I also don't understand.

Is this expected behavior?

**Comment by arobson** [comment]
@neverfox - whoa, this is definitely *not* expected behavior and reflects a relatively serious defect introduced in the 0.2.0 change set. I have only managed to narrow it down to the commit 490e680, which sadly is huge because it was a squash of several smaller commits that included refactoring and a lot of new tests.

If I go back to 84b8193, everything in the demo works great. I've been profiling the publisher (where the weird behavior is really stemming from) and have a few theories, but honestly, this is the weirdest thing I've seen in Node. I'll keep you posted as to how it's going. Thanks for reporting this one, it's not something that I would have thought to try creating a test case for.

**Comment by neverfox** [comment]
Sorry to hear that it was a real issue and not just my misunderstanding of AMQP. I wonder now if this is why I might have been seeing what I was seeing in #39. I'll try it again off the older commit you mentioned.
