### ISSUE TITLE
use of `batchAck`, and clearing out some messages while other still run?

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/wascally#47]
Regarding the fixes for #24 - it looks like there is a `wascally.batchAck()` method available now. Is that the correct method to use when I want to force acknowledgements to process?

I'm currently running in to a scenario where I have a very very very long (20+ minute) job running, with 5 other jobs that have completed. The other 5 jobs are sitting in unacked mode in rabbitmq, in spite of the work having been completed already.

In my scenario, it looks like Wascally is not processing the `ack` on those 5 messages, due to the 1 message that remains unack'd. Is that correct?

Assuming that is correct, will a call to `wascally.batchAck()` force the ack of those 5 messages to process, while the last one still runs?

also - there's not any documentation for the batchAck method that I can see.

**Comment by derickbailey** [comment]
In my testing of `batchAck` this is not fixing the situation that I am running in to. 

It looks like the fixes in #24 are allowing all messages to finish acking before closing the connection, which is definitely a good thing.

I was hoping that those fixes would also allow me to force `ack` back to the queues, as needed. However, it does not appear to be allowing this. Even when I call `batchAck` from my code, my messages are stuck in unacknowledged mode in the queue, until all outstanding messages are ack'd. 

I need to be able to ack messages in my queues, even when there is an outstanding message that has not yet had `msg.ack()` called on it.

**Comment by arobson** [comment]
There is no doc for batchAck because it is not for external consumers. It's always been there and is what is getting called periodically to trigger the process. You can't ack messages out of order and batch so no amount of calling it will ack messages when your app is hanging on to one.

Is there a reason you are concerned about those messages? They will resolve once the earlier message completes. If you are working with a consumer limit and that's why this is a problem, let me know.

**Comment by derickbailey** [comment]
Ok, yeah. I'll take that batchAck call out. I was reading through the code and I see what you're saying about it now. 

For my scenario and issues, yes this is due to queue limits.

### The Setup

In my job scheduling system, I have the idea of job "sizes" ... small, medium, large, etc. Each of these sizes is a rough approximation of how much horse power is needed to run the job on the servers. It's not an exact science, but there are some things that we know should be limited to only 1 or 2 things running concurrently.

In the current setup, a "small" job can have up to 6 parallel processes, and the process limit is implemented using queue limits. 

A situation that I eluded to above, is causing jobs to run sequentially at a certain point in our process, due to the batching of message ack.

### The Scenario Detail

We have 6 jobs set up to run as "small" jobs. 5 of the 6 should complete within a few seconds. The last one takes 20 minutes. It's still considered a "small" job, because it is not resource intensive, it is only long running. 

When the schedule kicks off, all 6 jobs are released for work. My worker agent picks up all 6 and begins running them immediately. The first 5 jobs complete within a few seconds, but the last job continues working and working and working for 20 minutes. 

The last job is not ack'd until it actually finishes. Because of this, all 6 message sit in unacknowledged mode, waiting for this last job to finish.

### Why This Is A Problem

We have about 10 more jobs that need to be run in this schedule, once that that last long-running job completes. If our short running steps were allowed to acknowledge in the queue, as they complete, then these remaining 10 jobs would run and very likely complete before that 20 minute job completes.

As it stands, the remainder of our jobs are stuck, waiting, not being processed, due to the batch acknowledgement of messages waiting for this long running job.

### A Temporary Workaround

Currently, the workaround is to put this long running job in it's own "size" - but that is not a workaround we want to keep around. There will be too many instances of this happening as we continue to migrate schedules off our old mainframe, on to this new scheduling system.

### What We Need

It is important for us to be able to acknowledge messages even when there are some that are not yet ack'd, so that our schedules can continue to run jobs in parallel, instead of the partially parallel, then serially, then parallel again way that is currently happening.

It would be good to either have the batch acknowlege ignore unack'd messages and go ahead and process the ones that are acked... or to provide an API that lets me force ack (again, ignoring the ones that are not yet acked).

**Comment by derickbailey** [comment]
after some discussion, we may be moving away from the current architecture that leaves messages unack'd. 

our current workaround is to stand up multiple instances of my agent process, with the limit set to 1 on each instance. doing that allowed my code to work as needed, but at the cost of a lot of running processed.

personally, i still feel the need to process the ack batch, while ignoring the ones that are not yet ack'd, is important. if one handler hangs and never acks a message, the rest of them should not be affected by this.

**Comment by arobson** [comment]
Yeah, what you really need is the ability to turn off batch acknowledgement for specific queues and then have the ack/nack/reject calls take place immediately.

The reason wascally does *not* do this is that it defaults for the fastest approach. In your case, you're processing things so slowly, you're not going to know a difference. Wascally's batching approach results in a 400% perf improvement over resolving each individual message. The thing is you __cannot__ batch ack out of order ever; trying to force it would just cause Rabbit to shut down your channel and return all unack'd messages back to the queue and you'd get back into the same state, try to force something, the channel would blow up again ...

I will take a look at adding this feature so that you can get back to doing things without having to run so many processes.

**Comment by derickbailey** [comment]
> Wascally's batching approach results in a 400% perf improvement over resolving each individual message.

WOAH! I knew it would have an improvement, but that's just darn impressive!

If there's anything I can do to help look in to this solution, let me know. If you have an idea for a direction and can point me down the path, I would love to help more than just opening tickets. :)

**Comment by arobson** [comment]
@derickbailey - that would be awesome :smile:, I would definitely appreciate the help.

### add a queue setting
First step would be to add a property to the queue settings to turn off batch behavior. I like `noBatch` myself.

### don't allow the setting to get passed to amqplib/rabbit
Add the new option as an arg on this line to prevent it from being sent to amqplib as a queue arg: https://github.com/LeanKit-Labs/wascally/blob/master/src/amqp/queue.js#L26

### add an operations factory specifically for noBatch
You'll need to create a 'version' of this function: https://github.com/LeanKit-Labs/wascally/blob/master/src/amqp/queue.js#L121-L134, call it something like `getNoBatchOps` and make sure that the `ack` function calls ack on the channel like on lines https://github.com/LeanKit-Labs/wascally/blob/master/src/amqp/queue.js#L121-L134 only pass `false` instead of inclusive! (failing this will make bad, bad things happen)

### don't allow the queue to attach to the batch signal if `noBatch` is set
This condition currently only kicks in when `noAck` is set: https://github.com/LeanKit-Labs/wascally/blob/master/src/amqp/queue.js#L155-L157, you'll need to update it to include this setting as well.

### pick the right set of resolution operations to attach to the message
Right now, this is a ternary but will need to be a little more sophisticated to support a new set of operations: https://github.com/LeanKit-Labs/wascally/blob/master/src/amqp/queue.js#L162. If `noBatch` is set, you'd call your `getNoBatchOps` function instead.

## testing
There isn't a straight-forward way to write behavioral tests around the queue.js module since it is the one handling all the direct channel interaction on behalf of the Rabbit queue. You'd end up having to mock a lot of the underlying lib and that'd get kinda involved. That's why there aren't behavior/unit tests for anything under the amqp folder.

The integration tests are all under /spec/integration/integration.spec.js. Add a new describe that will test this behavior by adding a new exchange, queue and binding to https://github.com/LeanKit-Labs/wascally/blob/master/spec/integration/configuration.js to use in your test. My suggestion for testing this is to effectively recreate your use case:
 
 1. set a consumer limit on the queue (say 5)
 2. publish 11 messages with increasing ids
 3. in the handler, only ack messages with ids > 1
 4. when your setup has processed 11 messages, call done
 5. assert that you received all 11 messages despite the queue limit and acking them manually out of sequence.

This will prove that in `noBatch` the handler is the master of the queue's fate and not the batching logic.

Let me know if I can help out in any other way. If you don't have time/change your mind, just let me know, I think explaining it was a good exercise for me anyway b/c now I think I could write the feature without too much additional work. #famousLastWords.

**Comment by derickbailey** [comment]
awesome! that's a far better technical spec than I've received from any business analyst in my career. thanks for the direction on this - off hand it all makes sense (having reviewed the code many times in recent weeks) :)

I'll likely work on this tomorrow afternoon... though, maybe tonight cause I drank too much caffeine and feel the need to code something.

**Comment by derickbailey** [comment]
pulling a note from #39 to get the tests up and running properly

`rabbitmq-plugins enable rabbitmq_consistent_hash_exchange`

**Comment by derickbailey** [comment]
i've got most of a test working at this point (learning a lot about your integration test suite in doing so). 

question: 

what would this assertion look like?

i have a handler set up to `message.ack()` on all messages except for the first one and I am keeping track of how many messages, total, that I receive in my handler.

does the assertion just look at `messageCount.should.equal(numMessagesSent)`?

just want to make sure i have the assertion correct

**Comment by derickbailey** [comment]
clearly my test is testing the right scenario... but my assertion is wrong because the test "passes" (false positive) even when the actual queue is stuck like this, forever:

![image](https://cloud.githubusercontent.com/assets/75190/6407800/7cc46c6e-be0d-11e4-862e-deb8780bc4c0.png)

**Comment by arobson** [comment]
@derickbailey try moving the `limit` to the queue from the exchange declaration, that should do it :)

**Comment by derickbailey** [comment]
#facepalm yeah, that would do it. :)

i got the spec correctly failing, so i'm on to putting in the fix!

**Comment by derickbailey** [comment]
regarding the "resolution operations" (noAck vs noBatch vs untracked):

if the noBatch setting is true, do I always call getNoBatchOps? what is noAck and noBatch are both true? wouldn't noAck override noBatch? If you have noAck set, then noBatch shouldn't do anything because you've said that you do no want to ack anything at all.

**Comment by arobson** [comment]
If noAck was chosen, then untracked ops are the ones you want. We still need to allow nack and reject, but ack should be a noOp. You can also choose to provide a boolean to the getNoBatchOps to indicate whether or not ack should actually be an ack or a noOp, your call :)

**Comment by derickbailey** [comment]
decided to go w/ the bool passed in to getBatchOps, to handle noAck and noBatch.

but at this point i'm having issues with this, and i'm not sure where. I've done my best to follow your suggested path, but i'm only seeing 1 message come through my handler in the spec, now. I'll try to keep digging. i may need some help spotting what i've got wrong, though. see next commit that i'm attaching

**Comment by derickbailey** [comment]
could the issue be here? https://github.com/derickbailey/wascally/blob/3cc9edc8e4f431743dafaeea972bbb07e64c30be/src/amqp/queue.js#L212

when I change this line to be `if ( data.activated && !ops.noAck && !ops.noBatch ) {` then I end up with a failure saying I got 5 out of 10 messages, instead of just 1 out of 10.

I'm not entirely sure what to do here, though. not sure if this really is the problem I'm seeing.

**Comment by derickbailey** [comment]
see previous commit ('prevent noBatch messages from going to unHandled'). this passes now, but I fear I'm doing something horrible.

**Comment by derickbailey** [comment]
I'd like to move this conversation over to PR #49 to start code reviewing and cleaning up anything I did wrong, handle any missing work (like documentation), etc. If that sounds good to you, @arobson, go ahead and close this ticket.

**Comment by arobson** [comment]
@derickbailey - thanks again for this. PR is merged and NPM is now at 0.2.3.
