### ISSUE TITLE
Is there a better way to get to channel prefetch?

### ISSUE THREAD

**Issue by jarrettmeyer** [LeanKit-Labs/wascally#53]
Currently, I am getting to the underlying channel prefetch function by using the following. Is there a better way to do this? It looks really odd to see `.channel.channel`.

```
var ch = rabbit.getQueue('my-queue').channel.channel;
ch.prefetch(1);
```

**Comment by derickbailey** [comment]
@jarrettmeyer you're trying to set the prefetch limit in this case, correct?

That can be done using the `limit` option on queue definitions:

```js
queues: [{
  name: "some.q",
  limit: 1 // set the prefetch limit
}]
```
Note that this is different than the `queueLimit` option which limits the number of messages in a queue.

It's a bit odd to see the channel prefetch limit set on the queue, but that's how it's done w/ wascally since wascally hides the idea of a channel behind the scenes. You essentially have 1 channel per queue, and the `limit` will set the prefetch limit of that channel.

hope that helps! (and I use this option a lot, by the way)

**Comment by jarrettmeyer** [comment]
Thanks for the info. Yes, that's quite hidden, and not what I expected. I tried setting `prefetch: 1`, but that didn't work.

**Comment by derickbailey** [comment]
Yeah, i agree. I submitted a PR w/ docs changes to explain this in the readme.
