### ISSUE TITLE
how to set the send interval

### ISSUE THREAD

**Issue by bboalimoe** [LeanKit-Labs/wascally#88]
some obj are nacked ... and it'll resend to consumer again ..but the default interval is too quick ..can  i set it a little slower ~ like 1 minute ~ thanks a lot

**Comment by derickbailey** [comment]
There's two ways to do this:

1) set up a dead-letter exchange (dlx). reject the message, instead of nacking it, so it will go through the dlx. route from the dlx to a queue that has a time to live setting for the message. once the ttl expires, have yet another dlx set up to re-route the message back to the original queue.

or

2) use the Delayed Message Exchange plugin https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/

option 1 is how everyone used to do it, until that plugin was released a few months ago. i'd go with the plugin, personally. :)

**Comment by bboalimoe** [comment]
@derickbailey  thanks ~  hiahia
