### ISSUE TITLE
Idle channel

### ISSUE THREAD

**Issue by BlueHotDog** [LeanKit-Labs/wascally#89]
Huge stability problems while trying to use this amazing library,
Once in a while the consumer becomes idle, nothing in the logs except an infinite loop of rebuilding the topology..

**Comment by arobson** [comment]
That's really odd. I wouldn't expect that unless there was an issue creating the topology or constant connection loss. Can you provide additional detail about the environment and versions? Anything you can provide that would help me reproduce the issue would be helpful.

**Comment by BlueHotDog** [comment]
Hi Alex,
I'm not sure what else can i help with, but let me try and give you the
full picture
The consumer works by taking messages, uncompressing them and publishing to
some other exchange,
I run the consumer via forever, and exit for any error.

But once in a while, the consumer disconnects, while the process which
forever monitors, is still live.

If i could only crash the process once it disconnects, that would be
definitely good enough.

**Comment by arobson** [comment]
@BlueHotDog would you try setting an environment variable to turn on the DEBUG logging? You can set it and run your service directly like this:

```bash
DEBUG=wascally* node ./path/myService.js
```

or by exporting it
```bash
export DEBUG=wascally*
```
And then re-starting via forever as long as you can see the logs somehow. What I'm interested in finding out is if there is some edge case where Rabbit is forcing a disconnection due to something in wascally or how you're calling something. There are quite a few scenarios where Rabbit will either close a channel or shut down the entire connection. It's also possible that your machine is losing connectivity to the Rabbit server. What environment are you running this in (cloud vs. local data center you control vs. VMs ...)

Wascally is designed to reconnect and re-establish topology. I've not seen it try to rebuild endlessly. The only things I can think of would be constant connection loss or one of the elements of the topology suddenly becoming invalid and preventing successful completion.

Wish I knew what else to try but without a lot more detail, these are my guesses :)

**Comment by arobson** [comment]
@BlueHotDog - any updates on this? Were you able to get things working to your satisfaction or did you have to use a different library to get things working?

**Comment by BlueHotDog** [comment]
Hey Alex, I've come up with a great setup, that looks somewhat like this:
``` var config = …
var rabbit = require( “wascally” ) ;

function setupConsumer (queueName , routingKey , handleMessageCallback) {
if (!queueName) throw new Error( “Must provide a valid `queueName` argument” ) ;
if (!routingKey) throw new Error( “Must provide a valid `routingKey` argument” ) ;
if (!handleMessageCallback) throw new Error( “Must provide a valid `handleMessage` argument” ) ;

this . rabbit = rabbit ;
this . rabbit . on ( “*.connection.closed” , function () {
console . log ( “connection closed” ) ;
process.exit() ;
}) ;

this . rabbit . on ( “*.connection.failed” , function () {
console . log ( “connection failed” ) ;
process.exit() ;
}) ;

return this . rabbit .configure(config).then( function () {
rabbit.nackOnError() ;
rabbit.nackUnhandled() ;

console . log ( “connected to “ + queueName + “ for routingKey “ + routingKey) ;
var handler = rabbit. handle (routingKey , handleMessageCallback) ;
handler.catch( function (err , msg) {
console . error ( “error “ + err + “ handling msg” ) ;
msg.nack() ;
process.exit( 10 ) ;
}) ;
rabbit.startSubscription(queueName) ;
} , function (ex) {
console . error (ex) ;
process.exit( 5 ) ;
}) ;
}

exports. setupConsumer = setupConsumer ;
``` The key elements are that you must listen to the disconnect events etc, since
if you dont, weird things happen..


On Thu, Oct 22, 2015 at 12:46 PM Alex Robson <notifications@github.com> wrote:
@BlueHotDog - any updates on this? Were you able to get things working to your satisfaction
or did you have to use a different library to get things working?

—
Reply to this email directly or view it on GitHub .
