### ISSUE TITLE
Is there a way to consume messages without a type?

### ISSUE THREAD

**Issue by puncha** [LeanKit-Labs/wascally#96]
We have different sub-systems to publish messages and they are using different clients, such as C#, Python and even Rest API. The messages they published doesn't has a type. We are routing messages to queues by amq.topic exchange. So I'm wondering if wascally can handle this kind of scenarios that consumes the messages from a specific queue rather than a specific type?

**Comment by arobson** [comment]
@puncha - presently, wascally expects a type specifically so that we don't end up having to create and manage separate queues per type. I might be able to make it so that wascally uses the topic set on the message in place of the type so that the topic is matched when assigning handlers. Do you think that would work for your specific use case?

**Comment by puncha** [comment]
@arobson , yeah, I think it can work for my case.

**Comment by joseph-onsip** [comment]
I'm encountering this problem as well. Unfortunately, I haven't yet been able to verify that the fix in #99 works for my use case (I'm still getting my bearings on wascally in general), but I think it's a step in the right direction.
